apiVersion: keymanagement.ibm/v1
kind: SecretTemplate
metadata:
  name: mysecret
  annotations:
    key-manager: key-protect
    key-protect/instanceId: b807dd59-fab6-45e5-b574-ff34f9426b97
    key-protect/region: us-east
spec:
  labels: {}
  annotations: {}
  values:
    - name: url
      value: https://ibm.com
    - name: username
      b64value: YWRtaW4K
    - name: password
      keyId: b73cfa91-c821-4df2-8ab1-84649d955557
