apiVersion: keymanagement.ibm/v1
kind: SecretTemplate
metadata:
  name: secure-handler-secret
  annotations:
    key-manager: key-protect
    key-protect/instanceId: b807dd59-fab6-45e5-b574-ff34f9426b97
    key-protect/region: us-east
spec:
  labels: {}
  annotations: {}
  values:
    - name: url
      value: https://ibm.com
    - name: username
      b64value: YWRtaW4=
    - name: password
      keyId: c112f191-1e07-46a1-968f-61ee6f753ace
