dependencies:
- name: inventory-management-svc-solution
  version: 0.0.3
  repository: https://artifactory-tools.appdev-cloudnative-ocp4-3b1fc50af0b2002f0241bdf5d2432efd-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/appdev-cloudnative-registry/
