global:
  ingressSubdomain: sandbox-ocp43-one-710233-eec031765f1e8f31f12a8fbbfd2e92f2-0000.eu-gb.containers.appdomain.cloud
  tlsSecretName: sandbox-ocp43-one-710233-eec031765f1e8f31f12a8fbbfd2e92f2-0000

inventory-management-svc-solution:
  replicaCount: 2
  
  # For OpenShift set route.enabled=true
  # For Kubernetes set route.enabled=false
  route:
    enabled: true
  
  # For OpenShift set ingress.enabled=false
  # For Kubernetes set ingress.enabled=true
  ingress:
    enabled: false
    tlsSecretName: sandbox-ocp43-one-710233-eec031765f1e8f31f12a8fbbfd2e92f2-0000

