global:
  ingressSubdomain: appdev-cloudnative-ocp4-3b1fc50af0b2002f0241bdf5d2432efd-0000.us-east.containers.appdomain.cloud
  tlsSecretName: appdev-cloudnative-ocp4-3b1fc50af0b2002f0241bdf5d2432efd-0000

inventory-management-svc-solution:
  replicaCount: 1
  
  # For OpenShift set route.enabled=true
  # For Kubernetes set route.enabled=false
  route:
    enabled: true
  
  # For OpenShift set ingress.enabled=false
  # For Kubernetes set ingress.enabled=true
  ingress:
    enabled: false
    tlsSecretName: appdev-cloudnative-ocp4-3b1fc50af0b2002f0241bdf5d2432efd-0000

